### ISSUE TITLE
DSpot json files are neither parsed nor visualized in the DSpot view

### ISSUE THREAD

**Issue by jesus-gorronogoitia** [STAMP-project/stamp-ide#1]
#### Characteristics
- **Issue Type**: bug
- **Reproducibility**: always
- **Severity**: minor
- **Tool/Service/Component**: DSpot Plugin for Eclipse, version 21/05/18
- **Execution Environment**: Linux Tumbleweed, Eclipse Oxygen.3a Release (4.7.3a)
- **Reporter**: Jesús Gorroñogoitia <jesus.gorronogoitia@atos.net>

#### Description
After executing a DSpot configuration, using the DSpot Wizard, DSpot completes successfully, as observed in the Console logs. Next, the DSpot View should be opened with the visualization of the produced json files, howewer, this view is not visualized. Instead, error logs show the following exception:

> java.io.FileNotFoundException: /home/yosu/Projects/STAMP/Git/dhell/dspot-out/hello_app.json (No such file or directory)
> 	at java.io.FileInputStream.open0(Native Method)
> 	at java.io.FileInputStream.open(FileInputStream.java:195)
> 	at java.io.FileInputStream.<init>(FileInputStream.java:138)
> 	at java.io.FileInputStream.<init>(FileInputStream.java:93)
> 	at java.io.FileReader.<init>(FileReader.java:58)
> 	at eu.stamp.wp4.dspot.view.DSpotView.parseJSON(DSpotView.java:74)
> 	at eu.stamp.wp4.dspot.execution.launch.DSpotEclipseLaunchConfigurationDelegate$1.run(DSpotEclipseLaunchConfigurationDelegate.java:175)
> 	at org.eclipse.ui.internal.PendingSyncExec.run(PendingSyncExec.java:58)
> 	at org.eclipse.ui.internal.UILockListener.doPendingWork(UILockListener.java:168)
> 	at org.eclipse.ui.internal.UISynchronizer.lambda$0(UISynchronizer.java:150)
> 	at org.eclipse.swt.widgets.RunnableLock.run(RunnableLock.java:37)
> 	at org.eclipse.swt.widgets.Synchronizer.runAsyncMessages(Synchronizer.java:182)
> 	at org.eclipse.swt.widgets.Display.runAsyncMessages(Display.java:4577)
> 	at org.eclipse.swt.widgets.Display.readAndDispatch(Display.java:4186)
> 	at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine$5.run(PartRenderingEngine.java:1150)
> 	at org.eclipse.core.databinding.observable.Realm.runWithDefault(Realm.java:336)
> 	at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine.run(PartRenderingEngine.java:1039)
> 	at org.eclipse.e4.ui.internal.workbench.E4Workbench.createAndRunUI(E4Workbench.java:153)
> 	at org.eclipse.ui.internal.Workbench.lambda$3(Workbench.java:680)
> 	at org.eclipse.core.databinding.observable.Realm.runWithDefault(Realm.java:336)
> 	at org.eclipse.ui.internal.Workbench.createAndRunWorkbench(Workbench.java:594)
> 	at org.eclipse.ui.PlatformUI.createAndRunWorkbench(PlatformUI.java:148)
> 	at org.eclipse.ui.internal.ide.application.IDEApplication.start(IDEApplication.java:151)
> 	at org.eclipse.equinox.internal.app.EclipseAppHandle.run(EclipseAppHandle.java:196)
> 	at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.runApplication(EclipseAppLauncher.java:134)
> 	at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.start(EclipseAppLauncher.java:104)
> 	at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:388)
> 	at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:243)
> 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
> 	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
> 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
> 	at java.lang.reflect.Method.invoke(Method.java:498)
> 	at org.eclipse.equinox.launcher.Main.invokeFramework(Main.java:653)
> 	at org.eclipse.equinox.launcher.Main.basicRun(Main.java:590)
> 	at org.eclipse.equinox.launcher.Main.run(Main.java:1499)
> 	at org.eclipse.equinox.launcher.Main.main(Main.java:1472)
> 

#### Steps to reproduce
Run DSpot Wizard with some configuration, selecting individual tests in Elipse Oxygen in Linux.
See below screenshot, showing the json files produced by DSpot in dspot-out folder

#### Other files and URLs
![dspot_out](https://user-images.githubusercontent.com/3658315/40307726-fd74726c-5d03-11e8-82c8-e30ee6f8f1a6.png)

#### [Help on issue template](https://github.com/STAMP-project/eclipse-ide/blob/master/.github/ISSUE_DOC.md) 
Preview to follow the link or open file .github/ISSUE_DOC.md

**Comment by RicardoTej** [comment]
Fixed, it was a problem building the path of the JSONs

**Comment by jesus-gorronogoitia** [comment]
In Linux, DSpot Wizard only parses the dhell.json file, but not the other json files with names like: _eu.stamp.examples.dhell.HelloAppTest_jacoco_instr_coverage.json_, 
and content like:

> {
>   "name": "eu.stamp.examples.dhell.HelloAppTest",
>   "nbOriginalTestCases": 7,
>   "initialInstructionCovered": 533,
>   "initialInstructionTotal": 1029,
>   "percentageinitialInstructionCovered": 51.79786200194364,
>   "amplifiedInstructionCovered": 539,
>   "amplifiedInstructionTotal": 1029,
>   "percentageamplifiedInstructionCovered": 52.38095238095239,
>   "testCases": []
> }

Please, give instructions to debug it in Linux and detect the cause of this misbehaviour. Thanks
