### ISSUE TITLE
proposal: rename repo from "eclipse-ide"  to "stamp-eclipse-plugins"

### ISSUE THREAD

**Issue by monperrus** [STAMP-project/stamp-ide#10]
To increase visibility, I propose to rename this repo to "stamp-eclipse-plugins".

**Comment by jesus-gorronogoitia** [comment]
Bonjour Martin,
I agree with changing the name to improve visibility, what about stamp-ide? more powerfull that stamp-eclipse-plugins, which gives the idea of individual plugins, while stamp-ide provides the idea of a complete testing environment

**Comment by jesus-gorronogoitia** [comment]
I've renamed this repository to "stamp-ide". If you still prefer "stamp-eclipse-plugins" let me know.

**Comment by monperrus** [comment]
Hi Yosu,

I really like something around 'stamp-ide', so that we can have plugins for other IDEs as well
(maybe intellij in the future).

what about stamp-ide-support?
