### ISSUE TITLE
UI: move "verbose", "comments" and "nominimize" to the Advanced config screen

### ISSUE THREAD

**Issue by monperrus** [STAMP-project/stamp-ide#11]
The "verbose", "comments" and "nominimize" are advanced config options.

Thus, I propose to put them in the Advanced config screen.

**Comment by jesus-gorronogoitia** [comment]
@RicardoTej please, could you take care? thanks

**Comment by RicardoTej** [comment]
Yes, I'm going to take care of it,
thanks.

**Comment by jesus-gorronogoitia** [comment]
Done. I will commit the new release asap
