### ISSUE TITLE
feature(descartes-eclipse UI): add option to create an issue on the issue tracker for specifying pseudo-tested methods

### ISSUE THREAD

**Issue by monperrus** [STAMP-project/stamp-ide#12]
Once Descartes finds a pseudo-tested method, the workflow is to create an issue so that a tester improves the test.

In the Descartes UI, where the report is shown, one could imagine a button that enables to automatically create an issue.

**Comment by jesus-gorronogoitia** [comment]
Bonjour Martin,
Do you mean to create a ticket in some external issue tracker (which one to support should be decided, mainly JIRA or Github) configured by the end-user? 
This implies that the Eclipse end user configure he/she external issue tracker and provides credentials, then she/he selects the Descartes issue and request to create issue from the data provided in Descartes report.
This should be done when the user inspect a particular Descartes issue.
Is this feature description fine with you?

**Comment by monperrus** [comment]
Hi Yosu,

> Do you mean to create a ticket in some external issue tracker (which one to support should be decided, mainly JIRA or Github) configured by the end-user?

Yes

> This implies that the Eclipse end user configure he/she external issue tracker and provides credentials, then she/he selects the Descartes issue and request to create issue from the data provided in Descartes report.

Not necessarily, a very lightweight solution is that the button simply opens a browser with a specific URL, where the URL means creating an issue eg `https://github.com/STAMP-project/stamp-ide/issues/new?subject=method+foo+pseudotested`

**Comment by jesus-gorronogoitia** [comment]
@RicardoTej is time to implement this feature
I will start with its specification (that we altogether can further refine):
On the Descartes view (HTML view) in Eclipse:
- Add a button to create a Jira issue with the content shown in the view. Ideally this should be the report about a pseudo tested method. An option is to enable this button when what it is shown in the view is the concrete detailed for a pseudo-tested method.
- Upon clicking this button, a form-based wizard is filled with the issue taken from the Descartes report. Additionally, the entire Descartes report (we have to decide which format: xml, json, html) can be added as an attachment. The user can fill in additional (and optional) JIRA issue fields and send the issue.
- The plugin will use the JIRA REST API to create a issue in the target JIRA instance defined by the user, using the configuration defined in the Eclipse preferences page, as well as his/her JIRA account, also declared in the corresponding Eclipse preferences page. The issue will be created with the information collected in previous steps.
- The target JIRA instance (endpoint) will be defined by users in a Descartes/JIRA configuration page in Eclipse preferences, implemented by the Descartes plugin. 
- In the same preferences page, the user could define his/her JIRA account. Password will be store using the Eclipse password management facility (key-ring)
- Upon issue creation, the user will be notified by plugin about the issue number, showing a link to navigate to it in an external browser.

**Comment by jesus-gorronogoitia** [comment]
Imaging this Descartes report (in html viewer)
![image](https://user-images.githubusercontent.com/3658315/52399763-71ec2e00-2abd-11e9-8deb-2c2a8732141d.png)
Once the user clicks on one issue (here there are only partially tested issues (I think we can support to create issues for any kind of issue, partially-tested, pseudo-tested), the user see this view:
![image](https://user-images.githubusercontent.com/3658315/52399850-bd9ed780-2abd-11e9-9ced-5660060d63f4.png)
In this situation, we can enable a button, located on the top right corner of the view to create a Jira issue with this Descartes issue.
In the Jira issue form, the issue title could be the following:
Method <pseudo-tested|partially tested>: method title
for example: Method partially tested: isEqual(eu.stamp_project.examples.dhell.MyStorage)

The description of the issues consist of the remaining content of Descartes report. Other issue fields could be filled with default values (or asked to the user to complete).

**Comment by jesus-gorronogoitia** [comment]
To detect whether or not the user have selected an issue (and therefore enabling the Jira issue creation button) we should be able to:
- get access to the html viewer source
- check the existence of common entities in the issue report, for instance the existence of fields in bold <b>class</b> or <b>package</b>

**Comment by jesus-gorronogoitia** [comment]
Some links to Eclipse programming technologies:
- creating/using preference pages: http://www.vogella.com/tutorials/EclipsePreferences/article.html
- encrypted management of passwords: http://blog.vogella.com/2011/09/22/eclipse-secure-storage-of-preferences/

**Comment by jesus-gorronogoitia** [comment]
JIRA Java API: https://developer.atlassian.com/server/jira/platform/java-apis/
@RicardoTej look for the entry in this documentation to create a JIRA issue using the Java API. Please, notice that a JIRA project should be created in advance to add the issue to it. If a project in Jira is not existing, we have two options:
- Ask the user to go to Jira and create one,
- Provide support in Descartes plugin to create a project, but I think we should not do this.

**Comment by jesus-gorronogoitia** [comment]
See JIRA Issue Editor pre-filled with data from Descartes
![image](https://user-images.githubusercontent.com/3658315/52638741-e87c9780-2ed2-11e9-8981-ef2bdf65e7c5.png)

**Comment by jesus-gorronogoitia** [comment]
Implemented in today release
