### ISSUE TITLE
CodeBase/TestSources could not be determined

### ISSUE THREAD

**Issue by assadOW2** [STAMP-project/stamp-ide#18]
#### Characteristics
- **Issue Type**: bug
- **Reproducibility**: always
- **Severity**: block
- **Tool/Service/Component**: DSPOT 
- **Execution Environment**: Ubuntu 16.04
- **Reporter**: Assad Montasser, assad.montasser@ow2.org

#### Description

I did a first execution of the tool on SAT4j core project, I had a failure in the console (a PitException). I tried to relaunch the tool in order to change parameters and I got this error box. So I did a Maven clean and a Maven build on the project. As you can see in the screen capture, build was successful. But I still have this error box. So I relaunched Eclipse and tried again, but still the same error box.

#### [Help on issue template](https://github.com/STAMP-project/eclipse-ide/blob/master/.github/ISSUE_DOC.md) 
Preview to follow the link or open 
![screenshot from 2018-09-05 17-29-56](https://user-images.githubusercontent.com/32927819/45104420-5eb1ec80-b132-11e8-8121-7f96b40b84a9.png)
file .github/ISSUE_DOC.md

**Comment by RicardoTej** [comment]
Good afternoon @assadOW2 

Would it be possible to get your Eclipse project in order to reproduce the unexpected behavior ?
Do you have the same problem using dhell ?

Thank you.

**Comment by assadOW2** [comment]
> Good afternoon @assadOW2
> 
> Would it be possible to get your Eclipse project in order to reproduce the unexpected behavior ?
> Do you have the same problem using dhell ?
> 
> Thank you.

Hi @RicardoTej ,

This is the project repository, I should have added it in first place, my mistake: 
https://gitlab.ow2.org/sat4j/sat4j/tree/master/org.sat4j.core

I didn't try dhell, I will do it and keep you informed if the problem persists.

**Comment by jesus-gorronogoitia** [comment]
Hi @assadOW2 @ltboye We have released a new version (1.0.0.201811141633) that should fix this issue. Please, update your Eclipse instance with the new DSpot and Descartes plugins and try again. Report to us your results. Thanks
