### ISSUE TITLE
feature: botsing Eclipse plugin

### ISSUE THREAD

**Issue by xdevroey** [STAMP-project/stamp-ide#19]
#### Characteristics
- **Issue Type**: feature
- **Reproducibility**: always
- **Severity**: feature
- **Tool/Service/Component**: botsing alpha-1
- **Execution Environment**: 
- **Reporter**: Xavier Devroey x.d.m.devroey@tudelft.nl

#### Description

Hi @jesus-gorronogoitia !

The very first alpha version of the new crash reproduction tool, called botsing (since we reimplemented everything, we changed the name), is available https://github.com/STAMP-project/botsing/. The main to call botsing is available [here](https://github.com/STAMP-project/botsing/blob/master/botsing-reproduction/src/main/java/eu/stamp/botsing/Main.java ) and the command line parameters are listed [here](https://github.com/STAMP-project/botsing/blob/master/botsing-reproduction/src/main/java/eu/stamp/botsing/CommandLineParameters.java). So very few parameters to provide in the end! :-)

#### Steps to reproduce
 NA
#### Other files and URLs

See https://github.com/STAMP-project/botsing/issues/4

#### [Help on issue template](https://github.com/STAMP-project/eclipse-ide/blob/master/.github/ISSUE_DOC.md) 
Preview to follow the link or open file .github/ISSUE_DOC.md

**Comment by jesus-gorronogoitia** [comment]
Hi @xdevroey 
In the Botsing configuration, I don't see the option to configure the output folder where generated crash replicating  test will be placed. 
- Could it be configured by users in future releases?
- If not, what is that default folder? I supposed it will be relative to the Botsing execution location.
Regards
Yosu

**Comment by xdevroey** [comment]
Ping @pderakhshanfar. Could you take a look?

**Comment by pderakhshanfar** [comment]
Hi @jesus-gorronogoitia 
The directory of output is set by `test_dir` in the [configuration file](https://github.com/STAMP-project/botsing/blob/master/botsing-reproduction/src/main/java/eu/stamp/botsing/config.properties). Also, you can pass this parameter to botsing from command line.

**Comment by jesus-gorronogoitia** [comment]
Hi @pderakhshanfar ,
Thanks for the answer.
We have a doubt, so the end user can pass parameters to Botsing using the CLI or place a config.properties (with those parameters) in the Botsing classpath? Do the CLI parameter override those in the config.properties?
