### ISSUE TITLE
Descartes plugin error

### ISSUE THREAD

**Issue by ltboye** [STAMP-project/stamp-ide#22]
#### Characteristics
- **Issue Type**: bug
- **Reproducibility**: always
- **Severity**: block
- **Tool/Service/Component**: Descartes Eclipse plugin 1.0.0.201809201413
- **Execution Environment**: Eclipse Photon, windows 10
- **Reporter**: Lars Thomas

#### Description
I have tried to use the Descartes Eclipse plugin. I made a configuration and enabled all mutators. Running, it is unable to compile. Complete console output below. I am able to run Descartes through Maven as per the Descartes instructions.

[INFO] Scanning for projects...
[INFO] 
[INFO] -----------------------< no.tellu.lib:tellulib >------------------------
[INFO] Building Tellu Utilities Library 3.0-SNAPSHOT
[INFO] --------------------------------[ jar ]---------------------------------
[INFO] 
[INFO] --- maven-clean-plugin:2.5:clean (default-clean) @ tellulib ---
[INFO] Deleting E:\Dev\tellu-github\tellulib\target
[INFO] 
[INFO] --- maven-resources-plugin:2.6:resources (default-resources) @ tellulib ---
[INFO] Using 'UTF-8' encoding to copy filtered resources.
[INFO] skip non existing resourceDirectory E:\Dev\tellu-github\tellulib\src\main\resources
[INFO] 
[INFO] --- maven-compiler-plugin:3.1:compile (default-compile) @ tellulib ---
[INFO] Changes detected - recompiling the module!
[INFO] Compiling 69 source files to E:\Dev\tellu-github\tellulib\target\classes
[INFO] -------------------------------------------------------------
[ERROR] COMPILATION ERROR : 
[INFO] -------------------------------------------------------------
[ERROR] No compiler is provided in this environment. Perhaps you are running on a JRE rather than a JDK?
[INFO] 1 error
[INFO] -------------------------------------------------------------
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 1.554 s
[INFO] Finished at: 2018-09-20T14:58:40+02:00
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-compiler-plugin:3.1:compile (default-compile) on project tellulib: Compilation failure
[ERROR] No compiler is provided in this environment. Perhaps you are running on a JRE rather than a JDK?
[ERROR] -> [Help 1]
[ERROR] 
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR] 
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoFailureException

#### [Help on issue template](https://github.com/STAMP-project/eclipse-ide/blob/master/.github/ISSUE_DOC.md) 
Preview to follow the link or open file .github/ISSUE_DOC.md

**Comment by jesus-gorronogoitia** [comment]
Hi @ltboye please, check in your Eclipse preferences/Java/Installed JREs that you has as default configured a JREs pointing to a JDK installation (but not a JRE installation). Maven need the complete JDK 1.8 (or superior). Since Descartes is working fine for you in the CLI (therefore Maven),  but not in Eclipse, I assume your Eclipse is using a JRE installation instead of a required JDK.

**Comment by ltboye** [comment]
You are right @jesus-gorronogoitia. I recently installed a new Eclipse to be compatible with the STAMP plugins, and it was using a JRE installation. Fixing that, it builds and runs through the tests, but then fails on invoking PIT.

The error message is:
Failed to execute goal org.pitest:pitest-maven:1.1.5:mutationCoverage (default-cli) on project tellulib: Execution default-cli of goal org.pitest:pitest-maven:1.1.5:mutationCoverage failed: Could not load requested engine descartes

It seems it tries to run the wrong version. In the created pom file, it has descartes version 1.2. That is also not the latest version. I have been running version 1.2.4, as per the instructions on GitHub. And it shouldn't be necessary to specify the version in the goal command.

**Comment by jesus-gorronogoitia** [comment]
Hi @ltboye Yes, this current Descartes plugin for Eclipse version used Descartes 1.2. I will ask @RicardoTej  to update it to use latest version 1.2.4

**Comment by jesus-gorronogoitia** [comment]
Hi @ltboye , please update your Descartes plugin for Eclipse. I've pushed a new version that fixes the Descartes version to use.
You should pull the repository, then go to Eclipse and undate Descartes plugin using your local STAMP update site. Please, let me know if this patch solves your issue.
Regards
Yosu

**Comment by ltboye** [comment]
Hi @jesus-gorronogoitia 
I updated the plugin. It still gives the same error, trying to run the goal org.pitest:pitest-maven:1.1.5:mutationCoverage. So it seems this old version number is hard-coded somewhere.

[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 18.453 s
[INFO] Finished at: 2018-09-25T09:49:27+02:00
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal org.pitest:pitest-maven:1.1.5:mutationCoverage (default-cli) on project tellulib: Execution default-cli of goal org.pitest:pitest-maven:1.1.5:mutationCoverage failed: Could not load requested engine descartes
[ERROR] 
[ERROR] Please copy and paste the information and the complete stacktrace below when reporting an issue
[ERROR] VM : Java HotSpot(TM) 64-Bit Server VM
[ERROR] Vendor : Oracle Corporation
[ERROR] Version : 25.172-b11
[ERROR] Uptime : 20217
[ERROR] Input -> 
[ERROR]  1 : -Dmaven.home=EMBEDDED
[ERROR]  2 : -Dclassworlds.conf=E:\Dev\workspace-github\.metadata\.plugins\org.eclipse.m2e.launching\launches\m2conf4557578683402160449.tmp
[ERROR]  3 : -Dmaven.multiModuleProjectDirectory=E:\Dev\tellu-github\tellulib
[ERROR]  4 : -Dfile.encoding=UTF-8
[ERROR] BootClassPathSupported : true
[ERROR] -> [Help 1]
[ERROR] 
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR] 
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/PluginExecutionException

**Comment by jesus-gorronogoitia** [comment]
Hi @ltboye 
I cannot reproduced your problem over DHell test project
Have you included any previous Descartes configuration in you pom.xml file?
This plugin takes your project pom.xml and adds the correct Descartes configuration, creating a new pom file with name <your_descartes_conf_name>_pom.xml, so your original pom.xml file is not override.
Please, remove any previous Descartes configuration from you original pom.xml, remove the other pom files generated by the plugin and try again. If it is still failing, please, send me the generated pom file.

**Comment by ltboye** [comment]
@jesus-gorronogoitia 
Yes, I had a Descartes config in the pom (in a profile). I removed it, and it worked!

It's strange, because my pom had a dependency on Descartes version 1.2.4, but the one generated by the Eclipse plugin has version 1.2. After removing mine, the generated version has 1.2.4!

It would be good if the plugin could handle a pom with existing config. It could be replaced in the generated pom.

I also miss the issue report, which is not generated through the plugin. Much of the point of using Descartes is to get this report. I will add a separate issue for this.

**Comment by jesus-gorronogoitia** [comment]
Hi @ltboye 
The new version of Descartes plugin creates a pom configuration based on existing one, that replaces the existing Descartes configuration with a new one that reflects the configuration established in the Wizard. This configuration is created in a different pom file, so not interfering with the existing one. Please, have a look and let us know.

**Comment by ltboye** [comment]
I updated the plugin. It still gives me the same error, trying to execute goal org.pitest:pitest-maven:1.1.5:mutationCoverage. So the version number has still not been removed from the goal.

**Comment by jesus-gorronogoitia** [comment]
Ok, I will ask @RicardoTej to create/modify existing PIT/Descartes configurations within default <build><plugins></plugins></build> and leave untouched those within <profiles><profile></profile></profiles>

**Comment by jesus-gorronogoitia** [comment]
Hi @ltboye We have released a new Descartes plugin version, 1.0.0.201811271630, which uses Maven profiles to configure and run Descartes, so it does not interfere with preexisting Maven PIT/Descartes configurations. Please, check this version works well with your use case

**Comment by ltboye** [comment]
Hi @jesus-gorronogoitia I tried the latest version, and it works fine. So I close the issue.
