### ISSUE TITLE
Generate Descartes issue report

### ISSUE THREAD

**Issue by ltboye** [STAMP-project/stamp-ide#25]
#### Characteristics
- **Issue Type**: feature
- **Reproducibility**:
- **Severity**: major
- **Tool/Service/Component**: Descartes plugin
- **Execution Environment**:
- **Reporter**: Lars Thomas Boye

#### Description
The issue report, listing pseudo-tested and partially-tested methods, is a big reason to use Descartes. It is currently not generated when using the Eclipse plugin. It is generated when <value>ISSUES</value> is included in outputFormats in the configuration.

**Comment by jesus-gorronogoitia** [comment]
Hi @ltboye 
We have added support to generate all Descartes reports. In this new release, the wizard lets users to specify the required reports (all enabled by default). At the moment, only the Descartes issues report is visualized, but Ricardo will implement asap support to visualize the PIT report as well. Note that the plugin asks Descartes to generate all the reports and they can be visualized by just clicking on their index.html files located in the target/pit-reports. Please, update the plugin and have a look. Thanks. Yosu
