### ISSUE TITLE
Botsing plugin: configure console output to file

### ISSUE THREAD

**Issue by luandrea** [STAMP-project/stamp-ide#31]
#### Characteristics
- **Issue Type**: feature
- **Reproducibility**: always
- **Severity**: feature
- **Tool/Service/Component**: Eclipse plugin for Botsing
- **Execution Environment**: All
- **Reporter**: Luca Andreatta luca.andreatta@eng.it

#### Description

It should be possible to configure Botsing plugin to have the output to be redirected to a file.

#### Relationships

Depends on [issues 28](https://github.com/STAMP-project/stamp-ide/issues/28)

#### [Help on issue template](https://github.com/STAMP-project/eclipse-ide/blob/master/.github/ISSUE_DOC.md) 
Preview to follow the link or open file .github/ISSUE_DOC.md

**Comment by jesus-gorronogoitia** [comment]
Hi @luandrea This feature has been implemented in version 1.0.0.201811271630 of Botsing plugin, which is available in GitHub.
